### ISSUE TITLE
Dowsnt work properly on win7 32bits

### ISSUE THREAD

**Issue by NikosEfthias** [alexbrainman/printer#1]
I am trying to test this package using CutePDF virtual printer it always prints an empty pdf and when I try XPS printer it does not open the save dialog just icon in the tray tells printing completed but nothing happens

**Comment by NikosEfthias** [comment]
```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"

	"github.com/alexbrainman/printer"
)

func main() {
	var file io.ReadCloser
	if len(os.Args) < 2 {
		log.Fatalln("Missing Filename")
	}
	defaultPrinterName, err := printer.Default()
	errChecker(err)
	file, err = os.Open(os.Args[1])
	errChecker(err)
	defer file.Close()
	prt, er := printer.Open(defaultPrinterName)
	errChecker(er)
	defer prt.Close()
	err = prt.StartDocument("Tombala", "RAW")
	errChecker(err)
	defer prt.EndDocument()
	err = prt.StartPage()
	errChecker(err)
	defer prt.EndPage()
	// io.Copy(prt, file)
	// fmt.Fprintln(prt, "test")
	fmt.Println(prt.Write([]byte("test")))
}
```

**Comment by jicg** [comment]
me too

**Comment by alexbrainman** [comment]
I have never used CutePDF virtual printer in my life. I do not know how to print to it. Perhaps you can ask CutePDF developers for help. You have the source code, for github.com/alexbrainman/printer, so you should be able to tell them what Windows API your program use. Perhaps they suggest something.

Alex

**Comment by NikosEfthias** [comment]
hi I tried also simple printing using windows XPS printer and a normal printer which was connected through USB neither succeeded

**Comment by alexbrainman** [comment]
I am sorry it does not work for you.
It works for all printers I use. Mind you, I always print text and nothing else.

Alex

**Comment by NikosEfthias** [comment]
well that could be the issue i sent pdf doc to printer however i also did
```go
fmt.Fprintln(printerWriter,"hello world")
```
and it was unsuccessfull too

**Comment by NikosEfthias** [comment]
well that could be the issue i sent pdf doc to printer however i also did 
```go
fmt.Fprintln(printerWriter,"hello world")
```
and it was unsuccessfull too

**Comment by alexbrainman** [comment]
> i sent pdf doc to printer

Copying PDF file to the printer will not work. Unless your printer understands PDF - I have not seen printers that do.

> fmt.Fprintln(printerWriter,"hello world")

Try and print some text file with this program I use myself (https://play.golang.org/p/tI-7R98hHa). See if that works for you.

Alex

**Comment by louishen91** [comment]
i get the same issue with @NikosEfthias, it does't work with a printer through USB. Should i set some params? @alexbrainman Thank u.

**Comment by alexbrainman** [comment]
> it does't work with a printer through USB

@louishen91 I do not know how to help you. Sorry.

Alex

**Comment by alexbrainman** [comment]
@pmtrilogic thank you for commenting here. I have made some changes to fix your problem. I published my changes here https://github.com/alexbrainman/printer/tree/fix1 I cannot test them on my computer, because my printer driver is not XPS-based. Please, try them and let me know how it went.

Thank you.

Alex

**Comment by pmtrilogic** [comment]
Hi Alex,

I have tried the new version on Windows 8.1 Pro, printing a raw PCL file through:
* A Type 3 printer driver that doesn't use XPSDrv.
* A Type 3 printer driver that does use XPSDrv.
* A Type 4 printer driver.

All of them printed correctly and there were no problems executing the code. I don't have a Windows 10 machine handy to test on, but I can't see any reason why it wouldn't also work there. Thanks for the update, which has done the trick!

BTW, I actually did all that testing with the same single printer (an Officejet 8620) as there are all types of driver (type 3 XPSDrv, type 3 non-XPSDrv and type 4), that produce PCL and the printer works with all of them as most PCL printers would. You can usually do similar things with other PDLs like postscript if you happen to have a postscript printer, so it's possible to test multiple types of driver even with only one printer just by selecting different drivers for it (the driver list in the Print Server Properties tells you which are Type 3 and which are Type 4, though not which Type 3 drivers use XPSDrv - you'd have to look at the properties for each driver and see which DLLs it uses to work that out).

I've also done limited testing before when I don't have the right type of printer at all, just setting it up to print to file. Obviously that's not a really good test, but it does confirm whether the job would go through and reach the printer if it was really there, and if the PDL is something reasonably readable like postscript you can look at the file and see whether the output looks sensible (or view it with a PDL viewer). Of course if you're on an older version of Windows that doesn't support the newer driver types then you're not going to be able to test them as they wouldn't even load, so none of the above would help in that case. Sorry if you're already familiar with all that sort of stuff, but if so maybe it will help someone else one day who isn't!

Thanks again for the quick update.

Pete

**Comment by alexbrainman** [comment]
> All of them printed correctly and there were no problems executing the code.

@pmtrilogic thank you for testing my change. Submitting my changes to the master.

Alex
