### ISSUE TITLE
[Question] Setting Font Size

### ISSUE THREAD

**Issue by Eskies** [alexbrainman/printer#14]
Hello, is there an option to set Font Size? I couldn't find it. It would be great if there's an option to set Font Size. I want to use it as printer server that could be used to print to many printer. It's only need to set fontsize base on which printer is used.

Thank you for your great code.

**Comment by alexbrainman** [comment]
> is there an option to set Font Size?

No, there is no option to Font Size in this package.

This package does not parse or understand data that you send to the printer. It just passes it to the printer as is.

Personally, I used this package to print text. And all printers I come across understand text. So this is good enough for me.

Sorry, but I cannot even provide any pointers to guide you along.

Alex
