### ISSUE TITLE
How to let the print machine send out the paper after printing?

### ISSUE THREAD

**Issue by qibobo** [alexbrainman/printer#23]
Hi Alex, when I use the print machine with windows directly, even if the document has only one line the print machine will print the line and then end the printing, then send the whole A4 paper out.
But when I use [this lib](https://github.com/alexbrainman/printer/blob/master/cmd/print/print.go), the print machine will print the one line but the A4 paper is still in the machine, so I can not get it out.
My question is that how to use this lib to make the print machine send out the A4 paper after my printing?

**Comment by alexbrainman** [comment]
@qibobo I don't know what your problem is.

Sorry.

Alex

**Comment by qibobo** [comment]
@alexbrainman Hi Alex, sorry for my poor description.
My problem is that:
When I just use windows to print a file, for example, the text file only contains 1 line "hello world", after I click "Print" button, the printer will print the "hello world" on a A4 paper and spit the paper, then I can get the A4 paper.

When I use the [printer's example](https://github.com/alexbrainman/printer/blob/master/cmd/print/print.go), I also print 1 line "hello world". Of course the printer machine print it, but it does not spit the A4 paper, and the paper is still in the printer machine, I can not pull it out.
Hope I have described clearly this time.

**Comment by alexbrainman** [comment]
@qibobo 

I understood you good first time.

> When I just use windows to print a file

How do "use windows to print a file"? You must be using some program. But even if you tell me which program you use, I will not be able to help you. Because I wouldn't know what the program does to provide functionality you see.

I hope I explained it will enough.

Alex

**Comment by qibobo** [comment]
@alexbrainman thank you!
