### ISSUE TITLE
Can not print chinese character

### ISSUE THREAD

**Issue by leedstyh** [alexbrainman/printer#4]
Hi Alex,

I can not print Chinese character (got bad prints), but English is OK. What might be the problem?

This is my testing code:

```
package main

import (
	"fmt"
	"log"

	"github.com/alexbrainman/printer"
)

func main() {
	testWindowPrinter()
}

func testWindowPrinter() {
	printLines("你好", "世界") // HERE, I got bad prints
	printLines("hello", "world")
}

func printLines(lines ...string) error {
	var defaultPrinter, err = printer.Default()
	if err != nil {
		log.Println(1, err.Error())
		return err
	}

	p, err := printer.Open(defaultPrinter)
	if err != nil {
		log.Println(2, err.Error())
		return err
	}
	defer p.Close()

	err = p.StartRawDocument("test")
	if err != nil {
		log.Println(3, err.Error())
		return err
	}
	defer p.EndDocument()

	err = p.StartPage()
	if err != nil {
		log.Println(4, err.Error())
		return err
	}

	for i := range lines {
		fmt.Fprintf(p, "%s\r\n", lines[i])
	}

	err = p.EndPage()
	if err != nil {
		log.Println(5, err.Error())
		return err
	}

	return nil
}

```

**Comment by alexbrainman** [comment]
@leedstyh 

Your program outputs utf8 text. github.com/alexbrainman/printer package just sends data directly to your printer as is. So, if your printer does not understand utf8, then it will not be able to print Chinese characters.

I do not know much about printers. So I do not know how to help you. Sorry.

Alex

**Comment by leedstyh** [comment]
Thank you @alexbrainman , you did help me. Follow your tip I encoded UTF8 string to GBK, using [this package](https://godoc.org/golang.org/x/text/encoding/simplifiedchinese), and it works well!

Nice project.

**Comment by alexbrainman** [comment]
> I encoded UTF8 string to GBK, using this package, and it works well!

Sounds good.

Alex
