### ISSUE TITLE
bit better documentation would be nice

### ISSUE THREAD

**Issue by slav123** [alexbrainman/printer#5]
Any chance for some examples ? the only example, how to use your package can be found here: https://stackoverflow.com/questions/29491148/go-how-can-i-print-to-an-actual-printer/29493081 any chance to get more examples ? if it's possible to print image for example ?

**Comment by alexbrainman** [comment]
> Any chance for some examples ?

What examples are your after. github.com/alexbrainman/printer has bunch of tests - you could look at those tests for some examples. There is also github.com/alexbrainman/printer/cmd/print program - that can be use to see how to use this package.

> the only example, how to use your package can be found here: https://stackoverflow.com/questions/29491148/go-how-can-i-print-to-an-actual-printer/29493081

That example is fine.

> ny chance to get more examples ?

What more examples do you need?

> if it's possible to print image for example ?

I do not know how to print image using this package.

Alex

**Comment by slav123** [comment]
Hi Alex,

I would love to see how you can change printing params ? Can you ? 

For example:
https://github.com/alexbrainman/printer/blob/master/cmd/print/print.go

you are managing multiple copies via loop, each printer during printing process has option to give no of copies - if there is any way to manage that ?

**Comment by alexbrainman** [comment]
> I would love to see how you can change printing params ? Can you ?

Your question is too general. What printer parameters would you like to change?

> you are managing multiple copies via loop, each printer during printing process has option to give no of copies - if there is any way to manage that ?

I do not know how to change number of copies to be printed. That is why I print same data multiple times.

Alex

**Comment by slav123** [comment]
All printer parameters - from generic like paper size, or mentioned earlier no of copies. To more detailed specific to each printer like: media type, print quality, colour correction and so on.

**Comment by alexbrainman** [comment]
> All printer parameters - from generic like paper size, or mentioned earlier no of copies. To more detailed specific to each printer like: media type, print quality, colour correction and so on.

I don't know of a way to change / read any of those parameters.
I never had the need for it.

Alex

**Comment by slav123** [comment]
Would you be able to explore this subjects (printing images / changing default printing parameters) ? I'm happy to pay for your time, and keep project open sourced ?

**Comment by alexbrainman** [comment]
> Would you be able to explore this subjects (printing images / changing default printing parameters) ?

Your requests are still too general. If you provide more details I will try and help, when I have free time.

> I'm happy to pay for your time, and keep project open sourced ?

I don't have much free time to sell. Sorry

Alex

**Comment by slav123** [comment]
ok
